{
 "title": "ali-gateway",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "系统监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"ali-gateway\"}",
       "legendFormat": "{{instance}} {{field}}"
      }
     ]
    },
    {
     "title": "磁盘使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (1 - (disk_free_bytes{job=\"ali-gateway\"} / disk_total_bytes{job=\"ali-gateway\"}))",
       "legendFormat": "{{instance}} {{field}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM堆使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(jvm_memory_used_bytes{job=\"ali-gateway\", area=\"heap\"}) by (instance) / sum(jvm_memory_max_bytes{job=\"ali-gateway\", area=\"heap\"}) by (instance))",
       "legendFormat": "{{instance}} {{field}}"
      }
     ]
    },
    {
     "title": "JVM线程状态",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(jvm_threads_states_threads{job=\"ali-gateway\"}) by (job, instance, state)",
       "legendFormat": "{{instance}} {{state}} {{field}}"
      },
      {
       "expr": "sum(jvm_threads_peak_threads {job=\"ali-gateway\"}) by (job, instance)",
       "legendFormat": "{{instance}} peak {{field}}"
      }
     ]
    },
    {
     "title": "GC次数统计",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(jvm_gc_pause_seconds_count{job=\"ali-gateway\"}) by (instance, action, cause)",
       "legendFormat": "{{instance}} {{cause}} {{field}}"
      }
     ]
    },
    {
     "title": "GC耗时统计",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(jvm_gc_pause_seconds_sum{job=\"ali-gateway\"}) by (instance, action, cause)",
       "legendFormat": "{{instance}} {{cause}} {{field}}"
      }
     ]
    }
   ]
  },
  {
   "title": "接口监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "服务QPS统计",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (service) (rate(ali_gateway_requests_timer_seconds_count[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "接口QPS统计",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (method, uri) (rate(ali_gateway_requests_timer_seconds_count[1m]))",
       "legendFormat": "[{{method}}] {{uri}} {{field}}"
      }
     ]
    },
    {
     "title": "接口最大耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(rate(ali_gateway_requests_timer_seconds_sum[5m])) by (uri, method)",
       "legendFormat": "[{{method}}]{{uri}}"
      }
     ]
    },
    {
     "title": "接口平均耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(ali_gateway_requests_timer_seconds_sum[5m])) by (uri, method)",
       "legendFormat": "[{{method}}]{{uri}}"
      }
     ]
    },
    {
     "title": "接口TP50耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(ali_gateway_requests_timer_seconds_bucket[5m])) by (le, uri, method))",
       "legendFormat": "[{{method}}] {{uri}}"
      }
     ]
    },
    {
     "title": "接口TP90耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(ali_gateway_requests_timer_seconds_bucket[5m])) by (le, uri, method))",
       "legendFormat": "[{{method}}] {{uri}}"
      }
     ]
    },
    {
     "title": "接口TP95耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(ali_gateway_requests_timer_seconds_bucket[5m])) by (le, uri, method))",
       "legendFormat": "[{{method}}] {{uri}}"
      }
     ]
    },
    {
     "title": "接口TP99耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(ali_gateway_requests_timer_seconds_bucket[5m])) by (le, uri, method))",
       "legendFormat": "[{{method}}] {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "日志监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "服务日志统计",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(logback_events_total{job=\"ali-gateway\"}) by (instance, level)",
       "legendFormat": "{{instance}} {{level}} {{field}}"
      }
     ]
    }
   ]
  },
  {
   "title": "业务监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "用户登陆统计",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "round(sum(increase(user_login_total[1d])))",
       "legendFormat": "每日登陆统计"
      }
     ]
    }
   ]
  }
 ]
}